language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t gusb-fedora -f contrib/ci/Dockerfile-fedora .
#  - docker build -t gusb-debian-stretch -f contrib/ci/Dockerfile-debian-stretch .

script:
  - docker run -t -v `pwd`:/build gusb-fedora ./contrib/ci/build_and_test.sh -Dtests=false
#  - docker run -t -v `pwd`:/build gusb-debian-stretch ./contrib/ci/build_and_test.sh -Dtests=false
